name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      HUSKY: 0
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: Install dependencies
        run: npm ci
      - name: Release
        env:
          GIT_AUTHOR_NAME: 'Simon Golms'
          GIT_AUTHOR_EMAIL: 'development@gol.ms'
          GIT_COMMITTER_NAME: 'Simon Golms'
          GIT_COMMITTER_EMAIL: 'development@gol.ms'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run release:ci
